# Generated by Django 3.2.9 on 2021-11-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('course_length', models.CharField(max_length=50)),
                ('course_count', models.IntegerField()),
                ('course_desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='video_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default='', max_length=250)),
                ('video_length', models.CharField(default='', max_length=250)),
                ('categroty', models.CharField(choices=[('تأسيس-وعي-مسلم-معاصر', 'تأسيس-وعي-مسلم-معاصر'), ('بيت-المسلم', 'بيت-المسلم'), ('شيخ-العمود-مدخل-إلي-علم-اللغة', 'شيخ-العمود-مدخل-إلي-علم-اللغة'), ('السيرة-النبوية-العهد-المكي', 'السيرة-النبوية-العهد-المكي'), ('تاريخ-الخلفاء-الراشدين', 'تاريخ-الخلفاء-الراشدين'), ('مدخل-للتاريخ-الاسلامي', 'مدخل-للتاريخ-الاسلامي')], default='', max_length=250)),
            ],
        ),
    ]
