# Generated by Django 3.2.9 on 2021-11-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completedCourses', '0002_alter_video_list_categroty'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categroty',
            field=models.CharField(choices=[('تأسيس-وعي-مسلم-معاصر', 'تأسيس-وعي-مسلم-معاصر'), ('السيرة-النبوية-العهد-المكي', 'السيرة-النبوية-العهد-المكي'), ('بيت-المسلم', 'بيت-المسلم'), ('تاريخ-الخلفاء-الراشدين', 'تاريخ-الخلفاء-الراشدين'), ('مدخل-للتاريخ-الاسلامي', 'مدخل-للتاريخ-الاسلامي'), ('شيخ-العمود-مدخل-إلي-علم-اللغة', 'شيخ-العمود-مدخل-إلي-علم-اللغة')], default='', max_length=250),
        ),
    ]
