# Generated by Django 3.2.7 on 2021-11-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completedCourses', '0003_course_categroty'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_list',
            name='vido_url',
            field=models.CharField(default='', max_length=400),
        ),
    ]
