# Generated by Django 3.2.9 on 2021-11-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completedCourses', '0004_video_list_vido_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categroty',
            field=models.CharField(choices=[('tases', 'tases'), ('السيرة-النبوية-العهد-المكي', 'السيرة-النبوية-العهد-المكي'), ('بيت-المسلم', 'بيت-المسلم'), ('تاريخ-الخلفاء-الراشدين', 'تاريخ-الخلفاء-الراشدين'), ('مدخل-للتاريخ-الاسلامي', 'مدخل-للتاريخ-الاسلامي'), ('شيخ-العمود-مدخل-إلي-علم-اللغة', 'شيخ-العمود-مدخل-إلي-علم-اللغة')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='video_list',
            name='categroty',
            field=models.CharField(choices=[('tases', 'tases'), ('السيرة-النبوية-العهد-المكي', 'السيرة-النبوية-العهد-المكي'), ('بيت-المسلم', 'بيت-المسلم'), ('تاريخ-الخلفاء-الراشدين', 'تاريخ-الخلفاء-الراشدين'), ('مدخل-للتاريخ-الاسلامي', 'مدخل-للتاريخ-الاسلامي'), ('شيخ-العمود-مدخل-إلي-علم-اللغة', 'شيخ-العمود-مدخل-إلي-علم-اللغة')], default='', max_length=250),
        ),
    ]
