# Generated by Django 3.2.9 on 2021-11-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_src', models.CharField(max_length=250)),
                ('audio_title', models.CharField(max_length=250)),
                ('audio_length', models.CharField(max_length=10)),
                ('audioShareLink', models.CharField(max_length=500)),
                ('audioDownloadLink', models.CharField(max_length=500)),
            ],
        ),
    ]
