# Generated by Django 3.2.7 on 2021-11-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='audioCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_title', models.CharField(default='', max_length=255)),
                ('categroty', models.CharField(choices=[('جذور-قرآنية', 'جذور-قرآنية'), ('ماذا-أتعلم-وكيف-أتعلم', 'ماذا-أتعلم-وكيف-أتعلم'), ('تأسيس-وعي-مسلم-معاصر-2', 'تأسيس-وعي-مسلم-معاصر-2'), ('الدورة-التعريفية-بالعلوم-الإسلامية', 'الدورة-التعريفية-بالعلوم-الإسلامية'), ('برنامج-برة-الصندوق', 'برنامج-برة-الصندوق'), ('مدخل-إلى-العلوم-الإنسانية', 'مدخل-إلى-العلوم-الإنسانية')], default='', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='categroty',
            field=models.CharField(choices=[('جذور-قرآنية', 'جذور-قرآنية'), ('ماذا-أتعلم-وكيف-أتعلم', 'ماذا-أتعلم-وكيف-أتعلم'), ('تأسيس-وعي-مسلم-معاصر-2', 'تأسيس-وعي-مسلم-معاصر-2'), ('الدورة-التعريفية-بالعلوم-الإسلامية', 'الدورة-التعريفية-بالعلوم-الإسلامية'), ('برنامج-برة-الصندوق', 'برنامج-برة-الصندوق'), ('مدخل-إلى-العلوم-الإنسانية', 'مدخل-إلى-العلوم-الإنسانية')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_src',
            field=models.CharField(max_length=850),
        ),
    ]
