# Generated by Django 3.2.9 on 2021-12-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=1000)),
                ('video_img', models.CharField(max_length=1000)),
            ],
        ),
    ]
