# Generated by Django 3.2.9 on 2021-12-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='video_dur',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
