# Generated by Django 3.2.9 on 2021-12-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_short_video_dur'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='categroty',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
